version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_gym
    ports:
      - "3306:3306"

  nestjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql